version: '3'
services:

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5000:1111"

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker

  redis:
    image: redis
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
