data-access:
  title: "Data Access"
  patterns:
    - "ProjectA/Data/**"
    - "Common/DataHelpers/*.cs"
    - "^.*Repository\\.cs$"

user-management:
  title: "User Management"
  patterns:
    - "ProjectB/Users/**"
    - "^.*User(Service|Controller)\\.cs$"

reports:
  title: "Reporting"
  patterns:
    - "Reports/**"
    - "^.*Report.*\\.cs$"
